### ISSUE TITLE
How to create symlinks for Windows

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/gondor#69]
Adding about syslink in readme. As many users have problem with that.

**Comment by namanrai** [comment]
@hereisnaman 
@samagragupta 
I would like to work on it. Can you please assign it to me?

**Comment by 0xnmn** [comment]
> @hereisnaman
> @samagragupta
> I would like to work on it. Can you please assign it to me?

You can start working, no need of assignment.

**Comment by namanrai** [comment]
Alright

**Comment by dibakar95** [comment]
Hi, I am new to this. Can anyone take up this issue? Do we need to just add steps to create a symlink in the README.md?
@hereisnaman @samagragupta

**Comment by rahgurung** [comment]
Hey @namanrai, I don't know if this is the right place to say this but few pieces of advice.
1) Always create a new branch from the `master` for each of your issues.
2) Create a PR with that branch to the `master` branch of upstream repo.
3) Don't claim an issue at the BOSS page if your PR isn't merged. You are just wasting both your and the BOSS claim page reviewer's time.
4) Instead of commenting, I will do this, just hit a PR (with good effort) because I noticed there is no assignment system here. It's `first solve, first get` here.
Best of luck.
